---
deployment:
  tasks:

    - export DEPLOYPATH=/home/ekatzgmo/Morse/
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp app.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
