---
deployment:
  tasks:

    - export DEPLOYPATH=/home/ekatzgmo/Morse/
    - cp -R templates $DEPLOYPATH
    - cp -R static $DEPLOYPATH
    - cp app.py $DEPLOYPATH
    - cp requirements.txt $DEPLOYPATH
